# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    admin.travel:
        class: AppBundle\Admin\TravelAdmin
        arguments: [~, AppBundle\Entity\Travel, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Voyages, group: Voyages }
    app.twig_extension:
        class: AppBundle\Twig\DashboardBlockExtension
        public: false
        tags:
            - { name: twig.extension }
